#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "${GV_DB_USER}" LOGIN PASSWORD '${GV_DB_PSWD}' SUPERUSER;
    CREATE DATABASE "${GV_DB_NAME}" OWNER "${GV_DB_USER}";
EOSQL
