apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: gross-view
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: gross-view
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard
