apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: gross-view
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: gross-view
spec:
  selector:
    app.kubernetes.io/name: vault
  ports:
    - name: http
      port: 8200
      targetPort: http
