apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: gross-view
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/part-of: gross-view
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
